# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://aminelch.github.io/"
defaultContentLanguage = "fr"
theme = "congo"

enableGitInfo = true

#googleAnalytics = "G-R491CBSHL3"
enableRobotsTXT = true
paginate = 50
summaryLength = 0

[permalinks]
  posts = "/p/:filename/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
