languageCode = "fr"
languageName = "French"
weight = 1

title = "Le blog de Amine LOUHICHI"
# logo = "/images/major_twitter_avatar.jpg"
copyright = "La totalit√© du contenu est soumise √† la licence [GPL3](https://www.gnu.org/licenses/quick-guide-gplv3.html)"
[params]
  isoCode = "fr"
  displayName = "fr"
  rtl = false
  dateFormat = "02 Jan 2006"
  description = "Mon petit m√©mo des expertises partag√©es : PHP, GNU/Linuxüêß, Architecture Applicative & Cie"

[author]
  name = "Amine LOUHICHI"
  image = "avatar.jpeg"
#  headline = ""
#  headline = "J‚Äô√©cris √† propos GNU/Linux, du d√©veloppement web et de la vie en g√©n√©ral."
  headline = "Mon petit m√©mo des expertises partag√©es : PHP, GNU/Linuxüêß, Architecture Applicative & Cie"
  bio = "Mon petit m√©mo des expertises partag√©es : PHP, GNU/Linuxüêß, Architecture Applicative & Cie"
  links = [
    { email = "mailto:mfauwxs1b@mozmail.com" },
    { gitlab = "https://gitlab.com/aminelch" },
    { dev = "https://dev.to/aminelch" },
    { twitter = "https://twitter.com/aminelch" },
    { linkedin = "https://linkedin.com/in/aminelch" },
  ]

#[params.post.reading_time]
#  one = "{{ .Count }} xxxxxxxx"
